"""Order tracking with IB event integration and database persistence.

Manages OrderStateMachine instances for each active order, bridges
IB order status events to state machine transitions, and persists
every transition to the database for a full audit trail.
"""

from __future__ import annotations

import structlog
from sqlalchemy import select
from statemachine.exceptions import TransitionNotAllowed

from trading.db.models import Order, OrderStateTransition
from trading.db.session import get_session
from trading.orders.state_machine import OrderStateMachine

logger = structlog.get_logger(component="order_tracker")

# Mapping from IB status strings to state machine event names.
# Each IB status maps to the event that should be fired on the
# state machine. The tracker handles idempotency and edge cases.
IB_STATUS_TO_EVENT: dict[str, str] = {
    "ApiPending": "submit",
    "PendingSubmit": "sent",
    "PreSubmitted": "pre_submit",
    "Submitted": "accept",
    "Filled": "fill",
    "Cancelled": "cancel",
    "ApiCancelled": "api_cancel",
    "Inactive": "reject",
}


class OrderTracker:
    """Manages order state machines and persists transitions to the database.

    Each tracked order has its own OrderStateMachine instance. The tracker
    provides two main interfaces:

    - ``transition()``: Send a named event directly to an order's state machine.
    - ``handle_ib_status()``: Translate an IB status string into the
      corresponding state machine event and fire it.

    Both methods persist every state transition as an OrderStateTransition
    record and update the order's current_state column.

    Attributes:
        session_factory: An async_sessionmaker for creating database sessions.
    """

    def __init__(self, session_factory) -> None:
        """Initialize the order tracker.

        Args:
            session_factory: An async_sessionmaker instance for DB access.
        """
        self.session_factory = session_factory
        self._machines: dict[str, OrderStateMachine] = {}
        self._logger = logger

    def create_order(self, order_id: str) -> OrderStateMachine:
        """Create and register a new state machine for an order.

        Args:
            order_id: The unique identifier for the order.

        Returns:
            The newly created OrderStateMachine instance.

        Raises:
            ValueError: If an order with this ID is already tracked.
        """
        if order_id in self._machines:
            raise ValueError(f"Order {order_id} is already tracked")

        machine = OrderStateMachine(order_id=order_id)
        self._machines[order_id] = machine
        self._logger.info("order_created", order_id=order_id)
        return machine

    def get_machine(self, order_id: str) -> OrderStateMachine | None:
        """Retrieve the state machine for a tracked order.

        Args:
            order_id: The unique identifier for the order.

        Returns:
            The OrderStateMachine if found, otherwise None.
        """
        return self._machines.get(order_id)

    async def transition(
        self, order_id: str, event: str, details: str | None = None
    ) -> str:
        """Send an event to an order's state machine and persist the transition.

        Args:
            order_id: The unique identifier for the order.
            event: The event name to fire (e.g., "submit", "fill").
            details: Optional details string to store with the transition.

        Returns:
            The new state value after the transition.

        Raises:
            KeyError: If the order_id is not tracked.
            TransitionNotAllowed: If the event is not valid from the current state.
        """
        machine = self._machines.get(order_id)
        if machine is None:
            raise KeyError(f"Order {order_id} is not tracked")

        from_state = machine.current_state_value

        try:
            machine.send(event)
        except TransitionNotAllowed:
            self._logger.warning(
                "transition_rejected",
                order_id=order_id,
                current_state=from_state,
                trigger=event,
            )
            raise

        # Consume and persist all transitions generated by this event
        transitions = machine.consume_transitions()
        for t in transitions:
            await self.persist_transition(
                order_id=order_id,
                from_state=t["from_state"],
                to_state=t["to_state"],
                event=t["event"],
                details=details,
            )

        new_state = machine.current_state_value
        self._logger.info(
            "transition_complete",
            order_id=order_id,
            from_state=from_state,
            to_state=new_state,
            trigger=event,
        )
        return new_state

    async def handle_ib_status(
        self, order_id: str, ib_status: str, details: str | None = None
    ) -> str:
        """Translate an IB status string and fire the corresponding event.

        Maps IB Gateway order status strings (e.g., "Submitted", "Filled")
        to state machine events and delegates to ``transition()``.

        Handles idempotency: if the machine is already in the target state,
        the call is logged and skipped without error.

        Args:
            order_id: The unique identifier for the order.
            ib_status: The IB status string (e.g., "Submitted", "Filled").
            details: Optional details string to store with the transition.

        Returns:
            The current state value after processing.

        Raises:
            KeyError: If the order_id is not tracked.
            ValueError: If the IB status string is not recognized.
        """
        event = IB_STATUS_TO_EVENT.get(ib_status)
        if event is None:
            raise ValueError(f"Unknown IB status: {ib_status!r}")

        machine = self._machines.get(order_id)
        if machine is None:
            raise KeyError(f"Order {order_id} is not tracked")

        self._logger.debug(
            "ib_status_received",
            order_id=order_id,
            ib_status=ib_status,
            mapped_trigger=event,
            current_state=machine.current_state_value,
        )

        try:
            return await self.transition(order_id, event, details=details)
        except TransitionNotAllowed:
            self._logger.warning(
                "ib_status_transition_rejected",
                order_id=order_id,
                ib_status=ib_status,
                mapped_trigger=event,
                current_state=machine.current_state_value,
            )
            # Return current state -- the IB status couldn't be applied
            return machine.current_state_value

    async def persist_transition(
        self,
        order_id: str,
        from_state: str | None,
        to_state: str,
        event: str,
        details: str | None = None,
    ) -> None:
        """Persist a state transition to the database.

        Creates an OrderStateTransition record and updates the order's
        current_state column within a single transaction.

        Args:
            order_id: The unique identifier for the order.
            from_state: The state before the transition (None for initial).
            to_state: The state after the transition.
            event: The event that triggered the transition.
            details: Optional details string for the audit record.
        """
        async with get_session(self.session_factory) as session:
            # Create the transition record
            transition = OrderStateTransition(
                order_id=order_id,
                from_state=from_state,
                to_state=to_state,
                event=event,
                details=details,
            )
            session.add(transition)

            # Update the order's current state
            result = await session.execute(
                select(Order).where(Order.id == order_id)
            )
            order = result.scalar_one_or_none()
            if order is not None:
                order.current_state = to_state
